name: Cleanup

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:    

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-old-releases@v0.2.0
        with:
          keep_latest: 14
          #older_than_days: 14     
          delete_release_assets: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean old tags
        run: |
          cutoff_date=$(date -d "14 days ago" --iso-8601=seconds)
          git tag -l | while read tag; do
            tag_date=$(git log -1 --format=%aI $tag)
            if [[ $tag_date < $cutoff_date ]]; then
              git tag -d $tag
              git push origin :refs/tags/$tag
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
